package id.atsiri.mymoviecatalogue;

import java.util.ArrayList;

public class TvShowsData {

    public static String[][] data = new String[][] {
            {"https://image.tmdb.org/t/p/w220_and_h330_face/mo0FP1GxOFZT4UDde7RFDz5APXF.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/dKxkwAJfGuznW8Hu0mhaDJtna0n.jpg","Arrow","73%","October 15, 2018","Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow."},
            {"https://image.tmdb.org/t/p/w220_and_h330_face/nVN7Dt0Xr78gnJepRsRLaLYklbY.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/sAzw6I1G9JUxm86KokIDdQeWtaq.jpg","Doom Patrol","58%","March 24, 2019","Set after the events of Titans, the Doom Patrol – consisting of Robotman, Negative Man, Elasti-Woman, and Crazy Jane, and led by Dr. Niles Caulder / The Chief – receive a mission from Cyborg that they cannot ignore and will change their lives."},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/3wx3EAMtqnbSLhGG8NrqXriCUIQ.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/iflq7ZJfso6WC7gk9l1tD3unWK.jpg","Dragon Ball","61%","February 25, 1986","Long ago in the mountains, a fighting master known as Gohan discovered a strange boy whom he named Goku. Gohan raised him and trained Goku in martial arts until he died. The young and very strong boy was on his own, but easily managed. Then one day, Goku met a teenage girl named Bulma, whose search for the dragon balls brought her to Goku's home. Together, they set off to find all seven dragon balls in an adventure."},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/58GKcwFV3lpVOGzybeMrrNOjHpz.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/m2lugAG39sO0yCcuxEAu4fY5u1o.jpg","Fairy Tail","71%","October 7, 2018","Lucy is a 17-year-old girl, who wants to be a full-fledged mage. One day when visiting Harujion Town, she meets Natsu, a young man who gets sick easily by any type of transportation. But Natsu isn't just any ordinary kid, he's a member of one of the world's most infamous mage guilds: Fairy Tail."},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/fki3kBlwJzFp8QohL43g9ReV455.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/jC1KqsFx8ZyqJyQa2Ohi7xgL7XC.jpg","The Flash","64%","October 9, 2018","After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash."},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/4XddcRDtnNjYmLRMYpbrhFxsbuq.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/mKBP1OCgCG0jw8DwVYlnYqVILtc.jpg","Gotham","67%","October 9, 2017","Before there was Batman, there was GOTHAM. Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker?"},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/lTVhwFcSHqN0Xv8HLxDHILtrwfX.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/iTHCRCwI810e39uy4QsByWmUN8z.jpg","Naruto","68%","March 24, 2002","A powerful beast known as the Nine-Tails attacks Konoha, the hidden leaf village in the Land of Fire, one of the Five Great Shinobi Nations in the Ninja World. In response, the leader of Konoha at the time, the Fourth Hokage, seals the fox inside the body of the new born Naruto Uzumaki, making Naruto a host of the beast; During this process it cost the fourth Hokage his life, requiring the Third Hokage to return from retirement in order to become leader of Konoha again. As a child, Naruto is shunned by the Konoha community, who treat Naruto as if he were the Nine-Tails that attacked the village."},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/eoj15m14Zpf2bUWXqNIs7itZK9w.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/nymeWHYQ1JaWP2wyNW5a5WHiDCd.jpg","NCIS","77%","September 25, 2018","From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has a shred of evidence connected to Navy and Marine Corps personnel, regardless of rank or position."},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/vqBsgL9nd2v04ZvCqPzwtckDdFD.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/3x1lVyxtsLKsZyR2E3qRe1EAXG4.jpg","Supergirl","67%","March 24, 2015","In season four, Supergirl is facing a bigger threat than she’s ever faced before – a new wave of anti-alien sentiment, spreading across National City that’s fomented by Agent Liberty. As Kara mentors a new reporter at CatCo, Nia Nal, and tries to use the power of the press to shine a light on the issues threatening to tear the city apart, Supergirl takes to the skies to battle the many villains who rise up in this era of divisiveness."},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/3iFm6Kz7iYoFaEcj4fLyZHAmTQA.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/o9OKe3M06QMLOzTl3l6GStYtnE9.jpg","Supernatural","58%","October 11, 2005","When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way."},
            {"https://image.tmdb.org/t/p/w188_and_h282_bestv2/bjU4tLlyp8W4yTB0Hqn8J1IDUnD.jpg","https://image.tmdb.org/t/p/w1000_and_h563_face/xOdA6paXYAWURfNNdYk7Oz62mxA.jpg","The Walking Dead","73%","March 30, 2010","Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way."}
    };

    public static ArrayList<TvShow> getListData(){
        ArrayList<TvShow> list = new ArrayList<>();
        for (String[] aData : data) {
            TvShow tvShow = new TvShow();
            tvShow.setPhoto(aData[0]);
            tvShow.setBanner(aData[1]);
            tvShow.setTitle(aData[2]);
            tvShow.setUserScore(aData[3]);
            tvShow.setTvShowDate(aData[4]);
            tvShow.setOverview(aData[5]);

            list.add(tvShow);
        }
        return list;
    }

}
